name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1 Hello
      id: test-1-hello
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test 1 Hello
        setup-command: npm install
        command: npm test
        timeout: 5
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1-HELLO_RESULTS: "${{steps.test-1-hello.outputs.result}}"
      with:
        runners: test-1-hello
